### ISSUE TITLE
Game hard crash on /reloadui , switch character, exit

### ISSUE THREAD

**Issue by georgetzel** [Twinkiee/AuraMastery#1]
The addition of "time remaining" option to triggers is awesome.

Unfortunately the duplicate initialization of ICComm and :shareChannel in AuraMasteryConfig.lua causes the client to hard-crash (with a memory error) on /reloadui.

Removing those extras fixes the issue and keeps the goodness.

**Comment by Twinkiee** [comment]
It's been fixed today.
https://forums.wildstar-online.com/forums/index.php?/topic/126382-game-update-19-may-2015/#entry1320853

On another positive side the original author of AuraMastery updated it on Curse so I won't make any further development until it's officially supported by the author himself.
